[tool.cibuildwheel]
# 构建的平台 (跳过3.8，某些依赖已不支持)
build = ["cp39-*", "cp310-*", "cp311-*", "cp312-*"]

# 跳过的构建
skip = [
    "*-win32",           # 跳过32位Windows
    "*-manylinux_i686",  # 跳过32位Linux  
    "*-musllinux_i686",  # 跳过32位musl Linux
    "pp*",               # 跳过PyPy
]

# 构建设置
build-verbosity = 1

# 环境变量 (Rust已在wheels.yml中预安装)
[tool.cibuildwheel.environment]
CARGO_NET_GIT_FETCH_WITH_CLI = "true"

# 测试设置
[tool.cibuildwheel.test-requires]
pytest = "*"

[tool.cibuildwheel.test-command]
python = "-c \"import hive_reader_rs; print('✅ 导入成功')\""
